spring.application.name=ledger-api-gateway
server.port=8081

spring.cloud.discovery.client.simple.instances.command-service[0].uri=http://localhost:8082/
spring.cloud.discovery.client.simple.instances.command-service[1].uri=http://localhost:8083/
spring.cloud.discovery.client.simple.instances.command-service[2].uri=http://localhost:8084/
spring.cloud.discovery.client.simple.instances.query-service[0].uri=http://localhost:8085/
spring.cloud.discovery.client.simple.instances.query-service[1].uri=http://localhost:8086/