spring.application.name=ledger-api-gateway
server.port=8081

# Command Service (Docker service name)
spring.cloud.discovery.client.simple.instances.command-service[0].uri=http://command-service:8082

# Query Service (Docker service name)
spring.cloud.discovery.client.simple.instances.query-service[0].uri=http://query-service:8094