spring.application.name=history-service
server.port=8091

spring.datasource.url=jdbc:postgresql://postgres-history:5432/history_db
spring.datasource.username=postgres
spring.datasource.password=raj_mistry01
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

#kafka configuration
spring.kafka.bootstrap-servers=kafka:29092
spring.kafka.consumer.group-id=history-projection-group
spring.kafka.consumer.auto-offset-reset=earliest