spring.application.name=query-service
server.port=8094


# Balance DB
balance.datasource.url=jdbc:postgresql://postgres-balance:5432/balance_db
balance.datasource.username=postgres
balance.datasource.password=raj_mistry01
balance.datasource.driver-class-name=org.postgresql.Driver

# History DB
history.datasource.url=jdbc:postgresql://postgres-history:5432/history_db
history.datasource.username=postgres
history.datasource.password=raj_mistry01
history.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

spring.data.redis.host=redis
spring.data.redis.port=6379