spring.application.name=query-service
server.port=8094


# Balance DB
balance.datasource.url=jdbc:postgresql://localhost:5432/balance_db
balance.datasource.username=postgres
balance.datasource.password=raj_mistry01
balance.datasource.driver-class-name=org.postgresql.Driver

# History DB
history.datasource.url=jdbc:postgresql://localhost:5432/history_db
history.datasource.username=postgres
history.datasource.password=raj_mistry01
history.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2