spring.application.name=balance-service
server.port=8090

spring.datasource.url=jdbc:postgresql://postgres-balance:5432/balance_db
spring.datasource.username=postgres
spring.datasource.password=raj_mistry01
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

#kafka configuration
spring.kafka.bootstrap-servers=kafka:29092
spring.kafka.consumer.group-id=balance-projection-group
spring.kafka.consumer.auto-offset-reset=earliest